### ISSUE TITLE
Could not find or load main class net.lax1dude.eaglercraft.v1_8.buildtools.gui.CompileLatestClientGUI

### ISSUE THREAD

**Issue by Mantas22XYT** [Eagler-CE/repo#6]
I tried to compile the repo on Windows only to get this error:
```
Error: Could not find or load main class net.lax1dude.eaglercraft.v1_8.buildtools.gui.CompileLatestClientGUI
Caused by: java.lang.ClassNotFoundException: net.lax1dude.eaglercraft.v1_8.buildtools.gui.CompileLatestClientGUI
The system cannot find the file specified.
The system cannot find the file specified.
Press any key to continue . . .
```
Using Oracle JDK 11.0.2

**Comment by vukle** [comment]
@Mantas22XYT I suggest using OpenJDK instead of Oracle Java. If it didn't fix, let me know.

**Comment by NuraadGit** [comment]
man fuck openjdk, use temurin or zulu

**Comment by Mantas22XYT** [comment]
Installed Azul JDK 11.0.20.1, issue persists.

**Comment by Mantas22XYT** [comment]
Also tried Temurin OpenJDK11U 11.0.20.1+1

**Comment by Mantas22XYT** [comment]
Fixed this by extracting the JDK's folders to the jdk folder in the project's root directory, cding into the buildtools directory and running `"../jdk/bin/java" -cp BuildTools.jar net.lax1dude.eaglercraft.v1_8.buildtools.gui.CompileLatestClientGUI`
