### ISSUE TITLE
goofy ass error

### ISSUE THREAD

**Issue by Hellscaped** [Eagler-CE/repo#9]
Running task 'init':

Scanning 'mcp918' folder...
Using temporary directory: /workspaces/EaglerCE-Hellscaped/eagbuild
Edit 'buildtools_config.json' to change

Notice: BuildTools is already initialized.

you must revert all changes in the 'patches' directory of
this repo back to the main repository's current commits,
otherwise the 'pullrequest' command wll not work properly

Do you want to re-initialize? [Y/n]: y

Extracting "/workspaces/EaglerCE-Hellscaped/./mcp918/mcp918.zip" to "/workspaces/EaglerCE-Hellscaped/eagbuild/ModCoderPack"...
   exceptor.json -> exceptor.json
   fields.csv -> fields.csv
   joined.exc -> joined.exc
   params.csv -> params.csv
   methods.csv -> methods.csv
   joined.srg -> joined.srg
   mcinjector.jar -> runtime.jar
   specialsource.jar -> runtime.jar
   fernflower.jar -> fernflower.jar

Generating "minecraft.srg" from "ModCoderPack"...
   Loaded 6514 symbols from methods.csv
   Loaded 6375 symbols from fields.csv
   - Deobf 2541 classes to "minecraft.srg"
   - Deobf 13441 methods to "minecraft.srg"
   - Deobf 6375 fields to "minecraft.srg"

Generating "minecraft.exc" from "ModCoderPack"...
   Loaded 8193 symbols from params.csv
   - Deobf 8181 params to "minecraft.exc"
   - Generate 6588 params to "minecraft.exc"

Extracting '/workspaces/EaglerCE-Hellscaped/./mcp918/1.8.8.jar" to "/workspaces/EaglerCE-Hellscaped/eagbuild/MinecraftSrc/minecraft_classes.jar"...
Extracted 2507 class files.

Running SpecialSource...
   [SpecialSource] Loading mappings
   [SpecialSource] 7 packages, 2541 classes, 8913 fields, 16419 methods
   [SpecialSource] Remapping final jar
SpecialSource completed successfully.

Running MCInjector...
MCInjector completed successfully.

Decompiling with Fernflower...
This will take a while, go get a drink or something lol.

Staying hydrated is important when u work on a fucked up project that
will make you angry enough put your fists through your bedroom wall

   [Fernflower] WARN:  Inconsistent inner class entries for net/minecraft/block/BlockSilverfish$EnumType!
   [Fernflower] WARN:  Inconsistent inner class entries for net/minecraft/block/BlockSilverfish$EnumType!
   [Fernflower] WARN:  Inconsistent inner class entries for net/minecraft/block/BlockSilverfish$EnumType!
   [Fernflower] WARN:  Inconsistent inner class entries for net/minecraft/block/BlockSilverfish$EnumType!
   [Fernflower] WARN:  Nested class net/minecraft/server/MinecraftServer$2 missing!
   [Fernflower] WARN:  Nested class net/minecraft/server/management/PreYggdrasilConverter$2 missing!
   [Fernflower] WARN:  Nested class net/minecraft/server/management/PreYggdrasilConverter$3 missing!
   [Fernflower] WARN:  Nested class net/minecraft/server/management/PreYggdrasilConverter$4 missing!
   [Fernflower] WARN:  Nested class net/minecraft/server/management/PreYggdrasilConverter$6 missing!
   [Fernflower] WARN:  Nested class net/minecraft/server/management/PreYggdrasilConverter$ConversionError missing!
Decompiler completed successfully.

Formatting source for patches...
   (Using default Eclipse format)
   .....................
Formatted 1612 classes.

Loading files from 'minecraft_src.jar'...
Patching files in 'minecraft_src.jar'...
   loaded 1115 patch files from the repo
   patching files...
   ................
Patched 1115 files
Restored 0 files
Replaced 0 files
Deleted 394 files

Adding javadoc...
   Loaded 6514 symbols from methods.csv
   Loaded 6375 symbols from fields.csv
Loading OpenGL enums: /lang/enums.json
Loading OpenGL enums: /lang/statemgr.json
Loaded 944 enums for 221 functions
   ................
Added 373 OpenGL enums
Added 4966 comments to methods
Added 317 comments to fields

Copying resources from '1.8.8.jar' into 'minecraft_res.jar'

Reading 'assetsIndexTransformer.json'...

Reading asset index '/workspaces/EaglerCE-Hellscaped/./mcp918/1.8.json'...
ERROR: failed to download additional assets from '1.8.json'!
org.json.JSONException: JSONObject["objects"] not found.
        at org.json.JSONObject.get(JSONObject.java:587)
        at org.json.JSONObject.getJSONObject(JSONObject.java:797)
        at net.lax1dude.eaglercraft.v1_8.buildtools.task.init.LoadResources.loadResources(LoadResources.java:83)
        at net.lax1dude.eaglercraft.v1_8.buildtools.task.init.DecompileMinecraft.decompileMinecraft(DecompileMinecraft.java:224)
        at net.lax1dude.eaglercraft.v1_8.buildtools.task.init.InitTask.initTask0(InitTask.java:148)
        at net.lax1dude.eaglercraft.v1_8.buildtools.task.init.InitTask.initTask(InitTask.java:34)
        at net.lax1dude.eaglercraft.v1_8.buildtools.EaglerBuildTools.main(EaglerBuildTools.java:69)
ERROR: Could not copy resources!
ERROR: could not decompile and patch 1.8.8.jar from "/workspaces/EaglerCE-Hellscaped/./mcp918/1.8.8.jar"!

why it do that

**Comment by OtterCodes102** [comment]
appears to be the wrong json file. are you sure its the asset index json and not the json from the versions folder?

**Comment by Hellscaped** [comment]
> should be in the assets/indexes folder i think.

downloaded it from the mc fandom page

**Comment by Hellscaped** [comment]
![image](https://github.com/Eagler-CE/repo/assets/72767525/cbc43fac-a7e8-46ed-8be3-7987ffe5ca34)
it looks fine

**Comment by Hellscaped** [comment]
bruh I used the wrong file LOL
had to get it from here https://launchermeta.mojang.com/v1/packages/f6ad102bcaa53b1a58358f16e376d548d44933ec/1.8.json
